INSERT INTO parametros_versoes (id, ativo, criado_por, snapshot)
VALUES (
  'v2026.04',
  true,
  'thiago',
  '{
    "_meta": {"versao":"v2026.04","criado_em":"2026-04-27","descricao":"Snapshot inicial calc_json v2"},
    "selic_anual": 14.0,
    "multiplos_setor": {"servicos_empresas":2.06,"educacao":2.18,"saude":2.12,"bem_estar":1.87,"beleza_estetica":1.76,"industria":1.72,"hospedagem":1.69,"logistica":1.67,"alimentacao":1.58,"servicos_locais":1.58,"varejo":1.52,"construcao":1.46},
    "ajuste_forma_atuacao": {"saas":0.82,"assinatura":0.46,"vende_governo":0.28,"distribuicao":0.12,"presta_servico":0.06,"produz_revende":-0.08,"fabricacao":-0.18,"revenda":-0.32},
    "fator_ise": [{"min":85,"max":100,"nome":"Estruturado","fator":1.30},{"min":70,"max":84,"nome":"Consolidado","fator":1.15},{"min":50,"max":69,"nome":"Operacional","fator":1.00},{"min":35,"max":49,"nome":"Dependente","fator":0.85},{"min":0,"max":34,"nome":"Embrionario","fator":0.70}],
    "pesos_ise": {"p1_financeiro":0.20,"p2_resultado":0.15,"p3_comercial":0.15,"p4_gestao":0.15,"p5_socio_dependencia":0.10,"p6_risco_legal":0.10,"p7_balanco":0.08,"p8_marca":0.07},
    "pesos_atratividade": {"ise":0.50,"setor":0.25,"crescimento":0.25},
    "score_setor_atratividade": {"servicos_empresas":9,"educacao":8,"saude":8,"beleza_estetica":7,"bem_estar":7,"varejo":6,"alimentacao":6,"hospedagem":6,"logistica":6,"industria":5,"servicos_locais":5,"construcao":4},
    "faixas_atratividade": [{"min":80,"max":100,"label":"Excelente"},{"min":65,"max":79,"label":"Boa"},{"min":50,"max":64,"label":"Moderada"},{"min":0,"max":49,"label":"Baixa"}],
    "faixas_crescimento": [{"min":30,"max":999,"score":10,"label":"Crescimento forte"},{"min":20,"max":29.9,"score":9,"label":"Crescimento solido"},{"min":10,"max":19.9,"score":7,"label":"Crescimento moderado"},{"min":5,"max":9.9,"score":5,"label":"Crescimento leve"},{"min":-5,"max":4.9,"score":4,"label":"Estavel"},{"min":-15,"max":-5.1,"score":2,"label":"Em queda"},{"min":-100,"max":-15.1,"score":0,"label":"Queda forte"}],
    "benchmarks_dre": {"servicos_empresas":{"cmv":5,"folha":35,"aluguel":5,"outros_cf":8,"mkt":3,"margem_op":30},"educacao":{"cmv":5,"folha":38,"aluguel":8,"outros_cf":8,"mkt":4,"margem_op":28},"saude":{"cmv":12,"folha":32,"aluguel":8,"outros_cf":8,"mkt":3,"margem_op":25},"bem_estar":{"cmv":5,"folha":30,"aluguel":12,"outros_cf":8,"mkt":4,"margem_op":22},"beleza_estetica":{"cmv":10,"folha":30,"aluguel":10,"outros_cf":8,"mkt":3,"margem_op":22},"industria":{"cmv":45,"folha":18,"aluguel":5,"outros_cf":8,"mkt":2,"margem_op":12},"hospedagem":{"cmv":18,"folha":25,"aluguel":12,"outros_cf":10,"mkt":4,"margem_op":18},"logistica":{"cmv":22,"folha":32,"aluguel":5,"outros_cf":10,"mkt":2,"margem_op":12},"alimentacao":{"cmv":32,"folha":22,"aluguel":9,"outros_cf":8,"mkt":3,"margem_op":15},"servicos_locais":{"cmv":12,"folha":28,"aluguel":8,"outros_cf":8,"mkt":2,"margem_op":18},"varejo":{"cmv":48,"folha":14,"aluguel":5,"outros_cf":6,"mkt":3,"margem_op":10},"construcao":{"cmv":38,"folha":22,"aluguel":4,"outros_cf":8,"mkt":2,"margem_op":10}},
    "modificadores_forma_atuacao_dre": {"presta_servico":{"cmv":-3,"folha":5,"aluguel":-1,"outros_cf":0,"mkt":0,"margem_op":3},"produz_revende":{"cmv":3,"folha":-3,"aluguel":2,"outros_cf":0,"mkt":0,"margem_op":-2},"fabricacao":{"cmv":5,"folha":-3,"aluguel":2,"outros_cf":0,"mkt":-1,"margem_op":-3},"revenda":{"cmv":8,"folha":-8,"aluguel":-1,"outros_cf":0,"mkt":1,"margem_op":-3},"distribuicao":{"cmv":5,"folha":-3,"aluguel":-2,"outros_cf":0,"mkt":-1,"margem_op":-2},"vende_governo":{"cmv":2,"folha":2,"aluguel":-1,"outros_cf":0,"mkt":-2,"margem_op":-3},"saas":{"cmv":-8,"folha":5,"aluguel":-4,"outros_cf":0,"mkt":3,"margem_op":8},"assinatura":{"cmv":-3,"folha":1,"aluguel":-1,"outros_cf":0,"mkt":2,"margem_op":4}},
    "benchmarks_indicadores": {"servicos_empresas":{"margem_bruta":65,"concentracao_max":18,"pmr":28,"pmp":30,"recorrencia_tipica":60},"educacao":{"margem_bruta":70,"concentracao_max":6,"pmr":10,"pmp":30,"recorrencia_tipica":90},"saude":{"margem_bruta":60,"concentracao_max":12,"pmr":25,"pmp":30,"recorrencia_tipica":50},"bem_estar":{"margem_bruta":75,"concentracao_max":2,"pmr":0,"pmp":30,"recorrencia_tipica":95},"beleza_estetica":{"margem_bruta":60,"concentracao_max":8,"pmr":0,"pmp":30,"recorrencia_tipica":40},"industria":{"margem_bruta":32,"concentracao_max":25,"pmr":40,"pmp":35,"recorrencia_tipica":30},"hospedagem":{"margem_bruta":55,"concentracao_max":8,"pmr":0,"pmp":30,"recorrencia_tipica":0},"logistica":{"margem_bruta":28,"concentracao_max":20,"pmr":30,"pmp":30,"recorrencia_tipica":50},"alimentacao":{"margem_bruta":58,"concentracao_max":8,"pmr":0,"pmp":25,"recorrencia_tipica":5},"servicos_locais":{"margem_bruta":55,"concentracao_max":12,"pmr":12,"pmp":30,"recorrencia_tipica":30},"varejo":{"margem_bruta":38,"concentracao_max":5,"pmr":25,"pmp":40,"recorrencia_tipica":5},"construcao":{"margem_bruta":22,"concentracao_max":35,"pmr":55,"pmp":40,"recorrencia_tipica":0}},
    "rat_por_setor": {"construcao":3.0,"industria":2.0,"logistica":2.0,"alimentacao":2.0,"beleza_estetica":1.5,"bem_estar":1.5,"hospedagem":1.5,"servicos_empresas":1.0,"educacao":1.0,"saude":1.0,"servicos_locais":1.0,"varejo":1.0}
  }'::jsonb
);

SELECT id, ativo, criado_em, jsonb_object_keys(snapshot)
FROM parametros_versoes
WHERE id = 'v2026.04';
